# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a0a4be0262d0ff32a46451350967b2689a3c69e5359bd36de659b196b5c22fe5fa9608f29889cc18d808cc1a99df555c120e57e2825fd93459b19558a87af47

test:
  secret_key_base: 78841e4c7a9f88d8919d8c436b1f33eba4be0c76e5766d5f2ad1ea08f0c3629a15846051d2d5a2eb3bf7c3afddf7a5accf3db0764e7ba1e9d64223360be3d142

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
